name: 'cov-insight'
description: 'cov-insight upload action'
inputs:
  repoId:
    description: 'repo id'
    required: false
    default: ${{ github.repository }}
  revHash:
    description: 'rev hash'
    required: false
    default: ${{ github.sha }}'
  sceneType:
    description: 'scene type'
    required: false
    default: 0
  sceneId:
    description: 'scene id'
    required: false
    default: 0
  dataType:
    description: 'data type'
    required: false
    default: "JACOCO"
  dataFile:
    description: 'data file'
    required: false
    default: "./target/jacoco.xml"
  backendUrl:
    description: 'backend url'
    required: false
    default: "http://127.0.0.1:9898"
runs:
  using: "composite"
  steps:
    - run: |
        cd ${{ github.action_path }}
        chmod +x ./upload.sh
        ./upload.sh
      shell: bash
